@echo off
echo Launching app...
if exist "C:\Program Files\R\R-3.3.2\bin\x64\R.exe" ("C:\Program Files\R\R-3.3.2\bin\x64\R.exe" CMD BATCH "Files\Launcher.R") ELSE "(C:\Program Files\R\R-3.3.2\bin\i386\R.exe" CMD BATCH "Files\Launcher.R")
echo In use...
